config/routes.rb
Countdown::Application.routes.draw do
  resources :tempos

end

app/models/tempo.rb
class Tempo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tempos_controller.rb
class TemposController < ApplicationController
  # GET /tempos
  # GET /tempos.xml
  def index
    @tempos = Tempo.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tempos }
    end
  end

  # GET /tempos/1
  # GET /tempos/1.xml
  def show
    @tempo = Tempo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tempo }
    end
  end

  # GET /tempos/new
  # GET /tempos/new.xml
  def new
    @tempo = Tempo.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tempo }
    end
  end

  # GET /tempos/1/edit
  def edit
    @tempo = Tempo.find(params[:id])
  end

  # POST /tempos
  # POST /tempos.xml
  def create
    @tempo = Tempo.new(params[:tempo])

    respond_to do |format|
      if @tempo.save
        format.html { redirect_to(@tempo, :notice => 'Tempo was successfully created.') }
        format.xml  { render :xml => @tempo, :status => :created, :location => @tempo }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tempo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tempos/1
  # PUT /tempos/1.xml
  def update
    @tempo = Tempo.find(params[:id])

    respond_to do |format|
      if @tempo.update_attributes(params[:tempo])
        format.html { redirect_to(@tempo, :notice => 'Tempo was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tempo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tempos/1
  # DELETE /tempos/1.xml
  def destroy
    @tempo = Tempo.find(params[:id])
    @tempo.destroy

    respond_to do |format|
      format.html { redirect_to(tempos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  require 'date'

  def quanto_falta(evento, time2)
    days, remaining = (evento-time2).to_i.abs.divmod(86400) 
    hours, remaining = remaining.divmod(3600)
    minutes, seconds = remaining.divmod(60)
    "#{days} dias, #{hours} horas, #{minutes} minutos, #{seconds} segundos"
  end
  
end

app/helpers/tempos_helper.rb
module TemposHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Countdown</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tempos/_form.html.erb
<%= form_for(@tempo) do |f| %>
  <% if @tempo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tempo.errors.count, "error") %> prohibited this tempo from being saved:</h2>

      <ul>
      <% @tempo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :evento %><br />
    <%= f.text_field :evento %>
  </div>
  <div class="field">
    <%= f.label :data_evento %><br />
    <%= f.date_select :data_evento %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tempos/edit.html.erb
<h1>Editing tempo</h1>

<%= render 'form' %>

<%= link_to 'Show', @tempo %> |
<%= link_to 'Back', tempos_path %>

app/views/tempos/index.html.erb
<h1>Listing tempos</h1>

<table>
  <tr>
    <th>Evento</th>
    <th>Data evento</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tempos.each do |tempo| %>
  <tr>
    <td><%= tempo.evento %></td>
    <td><%= tempo.data_evento %></td>
    <td><%= link_to 'Show', tempo %></td>
    <td><%= link_to 'Edit', edit_tempo_path(tempo) %></td>
    <td><%= link_to 'Destroy', tempo, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tempo', new_tempo_path %>

app/views/tempos/new.html.erb
<h1>New tempo</h1>

<%= render 'form' %>

<%= link_to 'Back', tempos_path %>

app/views/tempos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Evento:</b>
  <%= @tempo.evento %>
</p>

<p>
  <b>Data evento:</b>
  <%= @tempo.data_evento %>
</p>

<p>
  <b>Quanto falta?</b>
  <%= quanto_falta(Time.now, Time.(@tempo.data_evento)) %>
</p>

<%= link_to 'Edit', edit_tempo_path(@tempo) %> |
<%= link_to 'Back', tempos_path %>